// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVGlesAPxJv6dJZkUPCVBOlsP3vt3_xws',
    appId: '1:270556226556:web:51328d40111002616f4879',
    messagingSenderId: '270556226556',
    projectId: 'cross-device-clipboard-system',
    authDomain: 'cross-device-clipboard-system.firebaseapp.com',
    storageBucket: 'cross-device-clipboard-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKeOPuM6mxUGtiKDvtRjE45ly-29VUh3I',
    appId: '1:270556226556:android:4bb1ba70663f35946f4879',
    messagingSenderId: '270556226556',
    projectId: 'cross-device-clipboard-system',
    storageBucket: 'cross-device-clipboard-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWZgx1YG2d9WmlIMuyKeL2zMV_nCMc5vs',
    appId: '1:270556226556:ios:6cf914248c2684b16f4879',
    messagingSenderId: '270556226556',
    projectId: 'cross-device-clipboard-system',
    storageBucket: 'cross-device-clipboard-system.firebasestorage.app',
    iosBundleId: 'com.example.crossDevice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWZgx1YG2d9WmlIMuyKeL2zMV_nCMc5vs',
    appId: '1:270556226556:ios:6cf914248c2684b16f4879',
    messagingSenderId: '270556226556',
    projectId: 'cross-device-clipboard-system',
    storageBucket: 'cross-device-clipboard-system.firebasestorage.app',
    iosBundleId: 'com.example.crossDevice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVGlesAPxJv6dJZkUPCVBOlsP3vt3_xws',
    appId: '1:270556226556:web:51328d40111002616f4879',
    messagingSenderId: '270556226556',
    projectId: 'cross-device-clipboard-system',
    authDomain: 'cross-device-clipboard-system.firebaseapp.com',
    storageBucket: 'cross-device-clipboard-system.firebasestorage.app',
  );
}